<script type="text/javascript">
    jQuery(document).ready(function(){
        jQuery("#conteiner").css("background","none");
        news_comment();
        jQuery("#news_page_content").mCustomScrollbar({
            scrollInertia: 4,
            advanced:{
                updateOnContentResize:true
            }
        });

        jQuery.post('/default/ajax/getcomments', {link_id: <?php print $this->link_id; ?>}, function(resp){
            $(".popup_comment_wrap_ajax").empty().append(resp);
            $("#news_comments").mCustomScrollbar({
                scrollInertia: 4
            });
        }, 'html');
        $('.add_comm').live('click', function(){
            data = $(this).attr('data');
            ths = $(this).parent().parent();
            $(this).parent().parent().find('textarea[name=comment_text]').each(function(){
                commemt = $(this).val();
            });

            if(commemt != ''){
                $.post('/default/ajax/addcomment',{link_id:data,text:commemt}, function(resp){
                    $(ths).find(".popup_comment_wrap_ajax").empty().append(resp);
                    $("#news_comments").mCustomScrollbar({
                        scrollInertia: 4,
                        advanced:{
                            updateOnContentResize: true
                        }
                    });
                    $("#news_comments").mCustomScrollbar("scrollTo","bottom");
                }, 'html');
            }
        });
    });
</script>
<div class="dashboard-content wiki_page">
    <div id="news_page_container" class="news_page_container">
        <div class="news_page_body">
            <?php if(!$this->error): ?>
                <h1 class="page_title"><?php print $this->title;?></h1>
                <div class="news_page_contentainer">
                    <?php if($this->frame): ?>
                        <div id="news_page_frame_content">
                            <?php print $this->frame_content; ?>
                        </div>
                    <?php endif; ?>
                    <div id="news_page_content" class="news_page_content<?php if($this->frame) print ' hidden'; ?>">
                        <?php if($this->image): ?>
                            <div class="news_page_image"><img src="<?php print $this->image; ?>" /></div>
                        <?php endif; ?>
                        <?php if($this->content): ?>
                            <?php print $this->content;?>
                        <?php else: ?>
                            Aw Snap, This site doesn’t like us... We’ll take you to the <a href="<?=$this->url?>">page</a>! =]
                        <?php endif; ?>
                    </div>
                </div>
            <?php else: ?>
                <h1 class="page_title">Error</h1>
                <div class="news_page_contentainer">
                    You don't have permissions for view this news.
                </div>
            <?php endif; ?>
        </div>
        <?php if(!empty($_SESSION['user_name'])): ?>
            <div id="news_comment_wrapper" class="news_comment_wrapper">
                <a id="show_news_comment" href="javascript:void(0)" class="show_news_comment">Show</a>
                <div id="news_comments" class="news_comments hidden">
                    <h3 class="comment_h3">Comments</h3>
                    <div class="popup_comment_wrap_ajax"></div>
                    <div class="popup_form form-item" style="margin: 5px;">
                        <img src="<?=$_SESSION['user_pic']?>" class = "comment_img"/>
                        <textarea name="comment_text" class="form-textarea" placeholder="Comment"></textarea>
                    </div>

                    <div>
                        <input class="add_comm" type="button" value="Comment" data="<?=$this->link_id;?>">
                    </div>
                </div>
            </div>
        <?php endif; ?>
    </div>
</div>