<div class="popup_form" style="width: 420px; margin:0;">
    <div class="form-item_add_link">
        <span class="form-text_bg"></span>
        <input type="text" placeholder="Title" class="form-text" name="title" id="url_title" value="<?php print $this->title; ?>" />
    </div>
    <div class="form-item_add_link">
        <textarea id ="comment" name="comment" placeholder="Comment" class="form-textarea"></textarea>
    </div>
    <h3 class="popup_title2">Select any image</h3>
    <div class="form-item checkbox first">
        <?if(!empty($this->img_arr)):?>
            <?php foreach ($this->img_arr as $key => $value): ?>
                <div class="checkbox-item2">
                    <input id="img_link_<?= $key ?>" class="form-checkbox" type="radio" name="img_link" value="<?= $value ?>" />
                    <label for="img_link_<?= $key ?>"><img src="<?= $this->dir.$value ?>" alt="" height ="100px" width="100px" /></label>
                </div>
            <?php endforeach;?>
        <?endif;?>
        <?if(!empty($this->screenshot)):?>
            <div class="checkbox-item2">
                    <input id="img_link_scr" class="form-checkbox" type="radio" name="img_link" value="<?= $this->screenshot ?>" />
                    <label for="img_link_scr"><img src="<?= $this->screenshot ?>" alt="" height ="100px" width="100px" /></label>
            </div>
        <?endif;?>
        <div class="form-item btn_next">
            <input type="button" value="Save" class="form-submit" id="save_exp_link" />
        </div>
    </div>
</div>
