<?php
    $delete_block = '<div class="experience_setting_wrapper">';
        $delete_block .='<a href="javascript:void(0)" class="contextual-links-trigger">Settings</a>';
        $delete_block .='<ul class="contextual-links">';
            $delete_block .='<li class="block-configure"><a href="javascript:void(0)" class="del_exp_img delBookmark">Delete</a></li>';
        $delete_block .='</ul>';
    $delete_block .='</div>';
?>
<script src="<?php print $this->basePath; ?>/js/tabs_js.js"></script>
<script src="<?php print $this->basePath; ?>/js/jquery.isotope.min.js"></script>
<script type="text/javascript">
    jQuery(document).ready(function(){
        jQuery("#experience-content").mCustomScrollbar({
            scrollInertia: 4,
            advanced:{
                updateOnContentResize: true
            }
        });
        <?php foreach($this->links_arr as $item): ?>
            experience_tab('experience_block_tabs<?php print $item['id']; ?>');
        <?php endforeach; ?>
        <?php if(!empty($this->links_arr)): ?>
            jQuery('#experience_blocks').isotope({
                itemSelector : '.experience_block_item',
                animationEngine: 'jquery',
                containerStyle: {position: 'relative'},
                //layoutMode: 'fitRows',
                onLayout: function( $elems, instance ){
                    jQuery('#experience_blocks').toggleClass('variable-sizes').isotope('reLayout');
                }
            });
            jQuery('#experience_blocks').toggleClass('variable-sizes').isotope('reLayout');
        <?php endif; ?>

        popup_content();
        popup_link_share();
        manage_experience('experience_blocks', 'experience_block_item');
        manage_experience_settings('experience_block_item');
    });
</script>
<div class = "hidden">
    <form id="news_form" action ="/default/link/newspagefromlink" method="post">
        <input name ="title" id="newsfr_title" value=""/>
        <input name ="url" id="newsfr_url" value=""/>
        <input name ="thumbnail" id="newsfr_thumbnail" value=""/>
    </form>
</div>
<?php if(!$this->error): ?>
    <h1 class="page_title">
        <?php print $this->exp_title; ?>
        <?if(empty($this->blockAddLink)):?>
            <a href="javascript:void(0)" class="add_experience_btn_link" onclick="show_popup('addLink')">Add link</a>
        <?endif;?>
    </h1>
    <div class="add_experience_info">Add more bookmarks to have new look of experience page!</div>
    <div id="experience-content" class="experience-content">
        <div id="experience_blocks"  class="experience-content">
            <?php if(!empty($this->links_arr)): ?>
                <?php foreach($this->links_arr as $link): ?>
                    <?if(empty($link['old_rec'])):?>
                        <div class="experience_block_item">
                            <h3 class="experience_block_title"><?=$link['title']?></h3>
                            <?php print $delete_block; ?>
                            <div class="experience_block_image experience_popup_link" >
                                <div class="recommendation-item_btns">
                                    <a onclick="" class="recommendation_btns splyst" href="javascript:void(0)">Splyse</a>
                                    <a class="recommendation_btns share" href="javascript:void(0)">Share</a>
                                    <div class ="hidden"><?=$link['id']?></div>
                                </div>
                                <img src="<?php print $this->temp_dir.$link['thumbnail']; ?>" alt="" />
                            </div>
                            <div id="experience_block_tabs<?=$link['id']?>" class="experience_block_tabs">
                                <div class="tabs_experience">
                                    <a href="javascript:void(0)" id="experience_news<?=$link['id']?>" class="experience_tab tab_news active" title="News" onclick="getContent('news', 2, <?=$link['id']?>)">News</a>
                                    <a href="javascript:void(0)" id="experience_videos<?=$link['id']?>" class="experience_tab tab_video" title="Videos" onclick="getContent('videos', 2, <?=$link['id']?>)">Videos</a>
                                    <a href="javascript:void(0)" id="experience_images<?=$link['id']?>" class="experience_tab tab_image" title="Images" onclick="getContent('images', 2, <?=$link['id']?>)">Images</a>
                                    <a href="javascript:void(0)" id="experience_wikis<?=$link['id']?>" class="experience_tab tab_wiki" title="Wikipedia" onclick="getContent('wikis', 2, <?=$link['id']?>)">Wikipedia</a>
                                </div>
                                <div id="experience_news<?=$link['id']?>_content" class="tabs_experience_content active">
                                    <?if(!empty($link['news'])):?>
                                        <?php foreach($link['news'] as $news): ?>
                                            <div class="experience_content_item">
                                                <?php if(isset($news->image)): ?>
                                                    <div class="experience_content_item_image"><img src="<?=$news['image']?>" alt="" /></div>
                                                <?php endif; ?>
                                                <div class="experience_content_item_title"><?= $news['title']?></div>
                                                <div class="experience_content_item_desc"><?=$news['content']?></div>
                                                <a href="javascript:void(0)" class="experience_news_link" onclick ="opennews('<?=$news['url']?>', '<?=$news['title']?>'<?if(!empty($news->image)){echo ", '".$news['image']."'";}?> )"><?=$news['title']?></a>
                                            </div>
                                        <?php endforeach; ?>
                                        <a href="javascript:void(0)" class="more_link" onclick="getContent('news', 8, <?php print $link['id']; ?>)">More...</a>
                                        <div class="block_loader"><img src="/img/ajax-loader_grey.gif" height="32px" width="32px;" /></div>
                                    <?else:?>
                                        <div class="experience_content_item">
                                            No news
                                        </div>
                                    <?endif;?>
                                </div>
                                <div id="experience_videos<?=$link['id']?>_content" class="tabs_experience_content">
                                    <div class="block_loader"><img src="/img/ajax-loader_grey.gif" height="32px" width="32px;" /></div>
                                </div>
                                <div id="experience_images<?=$link['id']?>_content" class="tabs_experience_content">
                                    <div class="block_loader"><img src="/img/ajax-loader_grey.gif" height="32px" width="32px;" /></div>
                                </div>
                                <div id="experience_wikis<?=$link['id']?>_content" class="tabs_experience_content">
                                    <div class="block_loader"><img src="/img/ajax-loader_grey.gif" height="32px" width="32px;" /></div>
                                </div>
                            </div>
                            <div class="original_rec">
                                <h3 class="experience_popup_title hide_comment"><?=$link['title']?></h3>
                                <div class="experience_popup_left" style="position: relative;">
                                        <?if(!empty($link['thumbnail'])):?><img src="/static/<?=$_SESSION['user_id'].'/'.$link['thumbnail']; ?>" alt="" /><?endif;?>
                                    <div class="show_comm_btn active"></div>
                                </div>
                                <div class="experience-item_btns hide_comment" style="width: 100%; text-align: center;">
                                    <a class="experience_btns resplyst" href="javascript:void(0)">Splyse</a>
                                    <a class="experience_btns share" href="javascript:void(0)">Share</a>
                                </div>
                                <div class="experience_popup_right">
                                    <h3 class="experience_popup_title show_comment"><?=$link['title']?></h3>
                                    <div class="popup_comment_wrap_ajax"></div>
                                    <div class="popup_form form-item" style="margin: 5px;">
                                        <img src="<?=$_SESSION['user_pic']?>" class="comment_img"/>
                                        <textarea name ="comment_text" class="form-textarea" placeholder="Comment"></textarea>
                                    </div>

                                    <div class="experience-item_btns show_comment">
                                        <a class="experience_btns resplyst" href="javascript:void(0)">Splyse</a>
                                        <a class="experience_btns share" href="javascript:void(0)">Share</a>
                                    </div>
                                    <div>
                                        <input class="add_comm" type="button" value="Comment" data="<?=$link['id']?>" />
                                    </div>
                                </div>
                            </div>
                        </div>
                    <?else:?>
                        <div class="experience_block_item experience_popup">
                            <h3 class="experience_block_title"><?=$link['title']?></h3>
                            <?php print $delete_block; ?>
                            <div class="experience_block_image">
                                <?if($link['old_rec'] == 2): ?>
                                    <img src="<?=$link['url']; ?>" alt="" class="images" />
                                <?else: ?>
                                    <?if(!empty($link['thumbnail'])):?>
                                        <img src="<?=$link['thumbnail']; ?>" alt="" />
                                    <?else:?>
                                        <?if(!empty($link['description'])):?><?=$link['description']?><?endif;?>
                                    <?endif;?>
                                <?endif;?>
                            </div>
                            <div class="original">
                                <h3 class="experience_popup_title hide_comment"><?=$link['title']?></h3>
                                <div class="experience_popup_left" style="position: relative;">
                                    <?if($link['old_rec'] == 2): ?>
                                        <img src="<?=$link['url']; ?>" alt="" class="images" />
                                    <?elseif($link['old_rec'] == 3): ?>
                                        <object width="516" height="315">
                                            <param name="movie" value="http://www.youtube.com/v/<?=$link['url']; ?>?amp;version=3" />
                                            <param name="allowFullScreen" value="true" />
                                            <param name="allowscriptaccess" value="always" />
                                            <embed src="http://www.youtube.com/v/<?=$link['url'];?>?version=3" type="application/x-shockwave-flash" width="516" height="315" allowscriptaccess="always" allowfullscreen="true"></embed>
                                        </object>
                                    <?else: ?>
                                        <?if(!empty($link['thumbnail'])):?><img src="<?=$link['thumbnail']; ?>" alt="" /><?endif;?>
                                        <?if(!empty($link['description'])):?>
                                            <?=$link['description']?>
                                            <?if($link['old_rec'] == 1):?>
                                                <div class ="news_more_btn_div">
                                                    <a class="news_more_btn" href="/default/fblinks/news?id=<?=$link['id']?>">See more ...</a>
                                                </div>
                                            <?endif;?>
                                        <?endif;?>
                                    <?endif;?>
                                    <div class="show_comm_btn active"></div>
                                </div>
                                <div class="experience-item_btns hide_comment" style="width: 100%; text-align: center;">
                                    <a class="experience_btns resplyst" href="javascript:void(0)">Splyse</a>
                                    <a class="experience_btns share" href="javascript:void(0)">Share</a>
                                </div>
                                <div class="experience_popup_right">
                                    <h3 class="experience_popup_title show_comment"><?=$link['title']?></h3>
                                    <div class="popup_comment_wrap_ajax"></div>
                                    <div class="popup_form form-item" style="margin: 5px;">
                                        <img src="<?=$_SESSION['user_pic']?>" class="comment_img"/>
                                        <textarea name="comment_text" class="form-textarea" placeholder="Comment"></textarea>
                                    </div>

                                    <div class="experience-item_btns show_comment">
                                        <a class="experience_btns resplyst" href="javascript:void(0)">Splyse</a>
                                        <a class="experience_btns share" href="javascript:void(0)">Share</a>
                                    </div>
                                    <div>
                                        <input class="add_comm" type="button" onclick="scan()" value="Comment" data="<?=$link['id']?>" />
                                    </div>
                                </div>
                            </div>
                        </div>
                    <?endif;?>
                <?php endforeach; ?>
            <?php else: ?>
                <div class="empty_page">This experience has no links.</div>
            <?php endif;?>
        </div>
    </div>
<?php else: ?>
    <h1 class="page_title">Error</h1>
    <div class="experience-content">
        You don't have permissions for view this experience.
    </div>
<?php endif;?>
    
<script>
    $(document).ready(function(){
//        show_recom();
        $('.hide_comment').hide();
        $('.show_comment').show();
        var milk = 0;
        $('.show_comm_btn').live('click',function(){
            if(milk == 0){
                $('.hide_comment').show();
                $(this).removeClass('active');
                $('.show_comment').removeClass('active').hide();
                $('.experience_popup_right').hide('Clip');
                milk = 1
            }else{
                $('.hide_comment').hide();
                $(this).addClass('active');
                $('.show_comment').show();
                $('.experience_popup_right').show('Clip');
                milk = 0;
            }
        });
        $('.add_comm').live('click', function(){
            data = $(this).attr('data');
            ths = $(this).parent().parent();
            $(this).parent().parent().find('textarea[name=comment_text]').each(function(){
                commemt = $(this).val();
            });
            if(commemt != ''){
                $.post('/default/ajax/addcomment',{link_id:data,text:commemt}, function(resp){
                    $(ths).find(".popup_comment_wrap_ajax").empty().append(resp);
                    $(".popup_comment_wrap").mCustomScrollbar({
                        scrollInertia: 4,
                        advanced:{
                            updateOnContentResize: true
                        }
                    });
                    $(".popup_comment_wrap").mCustomScrollbar("scrollTo","bottom");
                }, 'html');
            }
        });
    });
    function opennews(url, title,thumb){
        $('#newsfr_title').val(title);
        $('#newsfr_url').val(url);
        $('#newsfr_thumbnail').val(thumb);
        $('#news_form').submit();
    }
</script>