<script type="text/javascript">
    jQuery(document).ready(function(){
        jQuery("#news_page_container").mCustomScrollbar({
            scrollInertia: 4,
            advanced:{
                updateOnContentResize:true
            }
        });
    });
</script>
<div class="dashboard-content wiki_page">
    <div id="news_page_container" class="news_page_container">
        <div class="video_page_body">
<!--            <h1 class="page_title fblinks">Close the professional football</h1>-->
<!--            <div class="recommendation-item_btns">-->
<!--                <a onclick="" class="recommendation_btns splyst" href="javascript:void(0)">Splyse</a>-->
<!--                <a onclick="" class="recommendation_btns share" href="javascript:void(0)">Share</a>-->
<!--            </div>-->
<!--            <object width="850" height="750">-->
<!--                <param value="http://www.youtube.com/v/u8bwe9Rjam0?amp;version=3" name="movie">-->
<!--                <param value="true" name="allowFullScreen">-->
<!--                <param value="always" name="allowscriptaccess">-->
<!--                <embed width="940" height="580" allowfullscreen="true" allowscriptaccess="always" type="application/x-shockwave-flash" src="http://www.youtube.com/v/u8bwe9Rjam0?version=3">-->
<!--            </object>-->
        </div>
    </div>
</div>