<script src="/js/tag-it.js" type="text/javascript" charset="utf-8"></script>
<link href="/css/jquery.ui.autocomplete.custom.css" rel="stylesheet" type="text/css">
<link href="/css/tagit.css" rel="stylesheet" type="text/css">
<!--<script src="/js/scroll/jquery.infinitescroll.min.js"></script>-->
<script src="/js/jquery.isotope.min.js"></script>

<script id="experienceTemplate" type="text/x-jquery-tmpl">
    <li class="recommendation_exp_title_item">
        <div id="exp_title_${id}" class="exp_title_item">
            <span class="exp_title_active"></span>
            <div class="exp_title_item_image">
                {{if exp_thumbnail}}
                    <img src="/static/<?=$_SESSION['user_id']?>/${exp_thumbnail}" />
                {{else}}
                    {{if exp_id == 64}}
                        <img src="/img/plus.png" />
                    {{else}}
                        <img src="/img/plus.jpg" />
                    {{/if}}
                {{/if}}
            </div>
            <div class="exp_title_item_name">${exp_title}</div>
        </div>
    </li>
</script>

<script type="text/javascript">
    var select_option = jQuery("#experienceTemplate").tmpl(<?=json_encode($this->experience); ?>);
    jQuery(document).ready(function(){
        resize_bg();
        jQuery("#recommendation_exp_title").append(select_option);
        show_recom_btns();
        show_recom();
        recom_exp_title();

//        jQuery('#recommendation_blocks').isotope({
//            itemSelector : '.recommendation_li',
//            animationEngine: 'jquery',
//            containerStyle: {position: 'relative'},
//            layoutMode: 'fitColumns'
//        });

        jQuery('#recommendation_blocks').isotope({
            itemSelector : '.recommendation_li',
            animationEngine: 'jquery',
            animationOptions: {
                duration: 250,
                easing: 'linear',
                queue: false
            },
            containerStyle: {position: 'relative'},
            layoutMode: 'masonryHorizontal',
            onLayout: function( $elems, instance ){
                jQuery('#recommendation_blocks').isotope('reLayout');
//                jQuery("#recommendation-content").mCustomScrollbar('update');

            }
        });
        jQuery("#recommendation-content").mCustomScrollbar({
            scrollInertia: 4,
            horizontalScroll: true,
            advanced:{
                updateOnContentResize: true,
                autoExpandHorizontalScroll: true
            },
            callbacks:{
                onTotalScroll: function(){
                    recommendation_page('/default/ajax/ajaxrecommendation', jQuery("#recommendation_blocks"));
                }
            }
        });
        jQuery('#recommendation_blocks').isotope('reLayout');
    });
</script>

<h1 class="page_title">What’s New for You</h1>
<div id="recommendation-content" class="recommendation-content">
    <?php if(!empty($this->recomendation_array)): ?>
        <ul id="recommendation_blocks" class="recommendation_blocks">
            <?php
                $content_row = $this->getHelper('Recommendation');
                print $content_row->Recommendation($this->recomendation_array);
            ?>
        </ul>
    <?php else: ?>
        <div class='empty_page'>You don't have any recommendations.</div>
    <?php endif; ?>
</div>
