<?if(!empty($this->comments)):?>
    <div class="popup_comment_wrap">
        <?foreach(json_decode($this->comments, true) as $comment):?>
            <?php if(!empty($comment)): ?>
                <?if(empty($this->fb_fr_arr)||(in_array($comment['fb_user_id'], $this->fb_fr_arr))):?>
                    <div class="popup_comment_item">
                        <div class="popup_comment_top">
                            <div class="comment_avatar"><img src="<?=$comment['user_pic']?>" width="50px" height="50px" /></div>
                            <div class="comment_user_name"><?=$comment['name']?></div>
                            <div class="comment_date"><?= date('F j, Y', strtotime($comment['date'])); ?></div>
                            <div class="comment_date"><?= date('h:i A', strtotime($comment['date'])); ?></div>
                        </div>
                        <div class="popup_comment_text"><?=$comment['data']?></div>
                    </div>
                <?endif?>
            <?endif?>
        <?endforeach;?>
    </div>
<?else:?>
    <div class="popup_nocomment">No comments. You can be first.</div>
<?endif;?>