<title>Splyst</title>
<link rel="shortcut icon" href="/" />
<meta name="title" content="<?=$this->shareTitle;?>" />
<meta name="description" content="<?=$this->shareMessage;?>" />
<meta http-equiv="Content-Type" content="text/html;charset=utf-8">
<?php 
    
    echo $this->headMeta()->appendHttpEquiv('Content-Type','text/html; charset=UTF-8')
                          ->appendHttpEquiv('Content-Language', 'en-US');
    echo $this->headLink()->appendStylesheet('/css/style_new.css?v=56')
                            ->appendStylesheet('/css/scroll/jquery.mCustomScrollbar.css?v=56')
                            ->appendStylesheet('/css/jquery-ui/jquery-ui.css');
    echo $this->headScript()->prependFile('/js/jquery-1.8.3.min.js')
                            ->appendFile('/js/jquery-ui-1.9.2.js')
                            ->appendFile('/js/scroll/jquery.mousewheel.min.js')
                            ->appendFile('/js/scroll/jquery.mCustomScrollbar.min.js')
                            ->appendFile('/js/validation-password.js')
                            ->appendFile('/js/jquery.cookie.js')
                            ->appendFile('/js/jquery.tmpl.min.js')
                            ->appendFile('/js/iscroll.js')
                            ->appendFile('/js/popup.js')
                            ->appendFile('/js/js.js');
      
?>
