<?php
    $controller = \Zend_Controller_Front::getInstance()->getRequest()->getControllerName();
    $module = \Zend_Controller_Front::getInstance()->getRequest()->getModuleName();
    $action = \Zend_Controller_Front::getInstance()->getRequest()->getActionName();
?>
<div class="header<?php if($controller =='index' && $module =='default') print ' static_pages'; ?>">
    <div class="logo">
        <a href="/default/recommendation/index">
            <img src="/img/logo.png" alt="splyst" />
        </a>
    </div>
    <?php if($controller =='index'&&$module =='default' && $action =='about'){ ?>
        <div class="header_title">About Us</div>
    <?php }elseif($controller =='index'&&$module =='default' && $action =='privacy'){ ?>
        <div class="header_title">Privacy Policy</div>
    <?php }elseif($controller =='index'&&$module =='default' && $action =='terms'){ ?>
        <div class="header_title">Terms of Service</div>
    <?php } ?>
    <?php if($controller =='index' && $module =='default'): ?>
        <div class="header_right">
            <a class="add_experience_btn_link back_btn" href="javascript: history.go(-1)">Back</a>
        </div>
    <?php else: ?>
        <div class="invite_btn_div">
            <div id="invite_btn" class="form-item btn_next">
                <input type="button" value="Invite" class="invite_btn" />
            </div>
        </div>
    <?php endif; ?>
</div>
<script>
    $(document).ready(function(){
        $('#invite_btn').click(function(){
            show_popup('guest');
        });
        $('#request_guest').click(function(){
            $('#error_guest').hide();
            if($('#guest-email').val() == '')
                $('#error_guest').empty().append('Fill the email field!').show();
            else if(ValidEmailAddress($('#guest-email').val())){
                $.post('/default/mail/invite', {'email':$('#guest-email').val()}, function(){}, 'json');
                close_popup();
                show_popup('guest_resp');
                setTimeout(" close_popup()", 4000);
            }else{
                $('#error_guest').empty().append('Incorrect email address!').show();
            }
        })
    })
</script>

