<?php
    $controller = \Zend_Controller_Front::getInstance()->getRequest()->getControllerName();
    $module = \Zend_Controller_Front::getInstance()->getRequest()->getModuleName();
    $action = \Zend_Controller_Front::getInstance()->getRequest()->getActionName();
?>
<div class="dashboard_block">
    <?if(!empty($_SESSION['user_id'])):?>
        <div class="dashboard-user">
            <div class="dashboard-user_photo"><img src="<?=$_SESSION['user_pic']?>" /></div>
            <div class="dashboard-user_name">
                <?=$_SESSION['user_name']?>
            </div>
            <div class="header-btns">
                <?php print $this->render("notifications.phtml"); ?>
            </div>
        </div>
    <?endif;?>
    <div class="dashboard-user_menu">
        <ul class="menu">
            <li class="menu_item<? if($controller == 'recommendation'&&$module == 'default') print ' active'; ?>"><a href="/default/recommendation/index">What's New<span id="recCounter" class="recCounter"></span></a></li>
            <li class="menu_item<? if($controller == 'dashboard'&&$module == 'default') print ' active'; ?>"><a href="/default/dashboard/index">Experiences</a></li>
            <?if($controller == 'dashboard' && $module == 'default'):?><li class="menu_item"><a href="javascript:void(0)" id="manageExperience">Manage experience</a></li><?endif;?>
            <?if($controller == 'dashboard' && $module == 'default'):?><li class="menu_item"><a href="javascript:void(0)" id="manageExperienceDone">Done</a></li><?endif;?>
            <li class="menu_item<? if($controller == 'collaborator'&&$module == 'default') print ' active'; ?>"><a href="/default/collaborator/index">People</a></li>
            <li class="menu_item"><a href="javascript:void(0)">Settings</a></li>
            <?php if(!empty($_SESSION['user_name'])): ?>
                <li class="menu_item"><a href="javascript:void(0)" onclick="logout()">Logout</a></li>
            <?php endif; ?>
        </ul>
    </div>
</div>
<div class="add_experience_block">
    <?php if($controller =='dashboard' && $module =='default' && $action =='index'): ?>
        <a href="javascript:void(0)" class="add_experience_btn" onclick="show_popup('addExp')">Add new experience</a>
    <?php elseif(($controller =='dashboard' && $module =='default' && $action =='experience')): ?>
        <a href="javascript:void(0)" class="add_experience_btn" onclick="show_popup('addLink')">Add new link</a>
    <?php endif;?>
</div>