<?php
    $front = Zend_Controller_Front::getInstance();
    $bootstrap = $front->getParam("bootstrap");
    $basePath = $bootstrap->getOption('basePath');
?>
<div id="splyst_overlay" class="splyst_overlay"></div>
<div id="splyst_spiner" class="splyst_spiner"><img src="<?php print $basePath; ?>/img/preloader.gif" width="50px" height="50px" /></div>
<div id="splyst_popup" class="splyst_popup">
    <div class="splyst_popups_wrap">
        <a href="javascript:void(0)" id="close_popup" class="close_popup" onclick="close_popup()">Close</a>

        <!-- start register block -->
        <div id="register_form_block" class="popup_form">
            <h3 class="popup_title">Register</h3>
            <form method="POST" action="" class="register_from" id="register-from" onkeypress="if(event.keyCode==13) popup_register();">
                <div class="form-item">
                    <span class="form-text_bg input_name"></span>
                    <input type="text" placeholder="User name" class="form-text" name="user_name" id="regis-user_name">
                </div>
                <div class="form-item">
                    <span class="form-text_bg input_email"></span>
                    <input type="text" placeholder="E-mail" class="form-text" name="email" id="regis-email">
                </div>
                <div class="form-item">
                    <span class="form-text_bg input_birthday"></span>
                    <input type="text" placeholder="Birthday" class="form-text" name="birthday" id="regis-birthday">
                </div>
                <div class="form-item">
                    <span class="form-text_bg input_pass"></span>
                    <input type="password" onkeyup="passwordStrength(this.value)" placeholder="Password" class="form-text" name="password" id="regis-password">
                </div>
                <div class="form-item erDiv">
                    <div class="error_block_wrap show_error"><div class="error_block_content"><h4>Error:</h4><ul><li class="invalid"></li></ul></div></div>
                </div>
                <div class="form-item">
                    <label for="passwordStrength" class="form-label">Password strength:</label>
                    <div id="passwordDescription">Medium</div>
                    <div class="strength3" id="passwordStrength"></div>
                </div>
                <div class="form-item">
                    <span class="form-text_bg input_pass"></span>
                    <input type="password" placeholder="Confirm password" class="form-text" name="confirm_password" id="confirm_password">
                </div>
                <div class="form-item">
                    <label class="form-label">Gender:</label>
                    <div class="radio-item">
                        <input type="radio" value="0" name="gender" id="regis-male" class="form-radio" /><label for="regis-male">Male</label>
                    </div>
                    <div class="radio-item">
                        <input type="radio" value="1" name="gender" id="regis-female" class="form-radio" /><label for="regis-female">Female</label>
                    </div>
                </div>
                <div class="form-item btn_next">
                    <input type="hidden" name="user_id" id="regis-user_id" />
                    <input type="hidden" name="fb_id" id="regis-fb_id" />
                    <input type="button" value="Next" class="form-submit" id="next" onclick="popup_register()" />
                </div>
            </form>
        </div>
        <!-- end register block -->

        <!-- start experience block -->
        <div id="experience_form_block" class="popup_form">
            <h3 class="popup_title" >Select experience</h3>
            <div id="experience-form" class="experience_form"></div>
        </div>
        <!-- end experience block -->

        <!--add experience block-->
        <div id="addExp_form_block" class="popup_form" onkeypress="if(event.keyCode==13) saveExp();">
            <h3 class="popup_title">Create new experience</h3>
            <div class="form-item">
                <span class="form-text_bg"></span>
                <input type="text" placeholder="Title" class="form-text" name="title" id="addExp_title" />
            </div>
                    
            <div class="form-item btn_next">
                <input type="button" value="Create" class="form-submit" onclick ="saveExp()">
            </div>
        </div>
        <!--end add experience block-->

        <!--add link block-->
        <div id="addLink_form_block" class="popup_form">
            <h3 class="popup_title">Insert new link</h3>
            <div class="addLink_form_main">
                <div class="form-item">
                    <span class="form-text_bg input_link"></span>
                    <input type="text" placeholder="Add a url ex: http://www.google.com" class="form-text" name="url" id="url_link" onkeypress="if(event.keyCode==13) scan();" />
                </div>
            </div>
            <div id ="url_error" style="display: none;">
                <span class="error_line"></span>
            </div>
            <div id="scan_btn" class="form-item btn_next">
                <input type="button" value="Scan" class="form-submit" onclick ="scan()" />
            </div>
        </div>
        <!--end add link block-->

        <!--start forget pass block-->
        <div id="pass_form_block" class="popup_form">
            <h3 class="popup_title">Forget Password</h3>
            <div class="form-item">
                <span class="form-text_bg input_email"></span>
                <input id="forget_email" type="text" placeholder="E-mail" class="form-text" name="forget_email" onkeypress="if(event.keyCode==13) forget_password('send');" />
            </div>
            <div class="form-item erDiv">
                <div class="error_block_wrap show_error"><div class="error_block_content"><h4>Error:</h4><ul><li class="invalid"></li></ul></div></div>
            </div>
            <div class="form-item btn_next">
                <input type="button" value="Send" class="form-submit" onclick ="forget_password('send')" />
            </div>
        </div>
        <!--end forget pass block-->

        <!--start message block-->
        <div id="mess_from_block" class="popup_form"></div>
        <!--end message block-->

        <!--start message block-->
        <div id="media_form_block" class="popup_form">
            <h3 id="media_block_title" class="popup_title"></h3>
            <div id="media_block_content" class="media_block_content"></div>
        </div>
        <!--end message block-->

        <!--start splyst button block-->
        <div id="recommendation_btn_form_block" class="popup_form">
            <h3 class="popup_title">Add link to Experience</h3>
            <div id="splyst-button-form">
                <div class="form-item">
                    <ul id="recommendation_exp_title" class="recommendation_exp_title">
                        <li class="recommendation_exp_title_item">
                            <div id="exp_title_0" class="exp_title_item">
                                <span class="exp_title_active"></span>
                                <div class="exp_title_item_image">
                                    <img src="/img/new_exp.png" />
                                </div>
                            </div>
                            <div class="exp_title_item_name">
                                <input id="exp_title_0_name" type="text" placeholder="Name Experience" class="form-text" />
                            </div>
                        </li>
                    </ul>
                </div>
                <div class="form-item" id="exp-title">
                    <input type="hidden"  class="form-text" name="url" id="url_spl_btn" value="" />
                    <input type="hidden"  class="form-text" name="text" id="text_spl_btn" value="" />
                    <input type="hidden"  class="form-text" name="img" id="img_spl_btn" value="" />
                    <input type="hidden"  class="form-text" name="img" id="title_spl_btn" value="" />
                </div>
                <div id="recommendation_form_error" class="form-item hidden form_error">
                    You must select experience or create new.
                </div>
                <div class="form-item btn_next">
                    <input type="button" value="Splyse" class="form-submit" onclick ="saveSplystBtn()" />
                </div>
            </div>
        </div>
        <!--end splyst button block-->

        <!--start share button block-->
        <div id="share_btn_form_block" class="popup_form">
            <h3 id="share_btn_block_title" class="popup_title">Share to Friends</h3>
            <div class="block_loader"><img src="/img/ajax-loader_grey.gif" height="32px" width="32px;" /></div>
            <div id="share_btn_block_content" class="share_btn_block_content"></div>
        </div>
        <!--end share button block-->

        <!--start invite block-->
        <div id="invite_form_block" class="popup_form">
            <h3 id="invite_block_title" class="popup_title">Invite your friends</h3>
            <div id="invite_block_content" class="invite_block_content">
                <div class="form-item">
                    <ul id="friends_invite_names"></ul>
                    <ul class="tagit ui-widget ui-widget-content ui-corner-all"><li id="tagit"></li></ul>
                </div>
                <div class="form-item">
                    <textarea name="invite_message">test invite</textarea>
                </div>
                <div class="form-item btn_next">
                    <input type="button" value="Send invite" class="form-submit" onclick ="sendInvite('send')" />
                </div>
            </div>
        </div>
        <!--end invite block-->

        <!--start invite block for guest page-->
        <div id="guest_form_block" class="popup_form">
            <h3 id="invite_block_title" class="popup_title">Invite to splyst</h3>
            <div id="invite_block_content" class="invite_block_content">
                <div style="padding-bottom: 13px">Please enter your email adress</div>
                <div class="form-item">
                    <span class="form-text_bg input_email"></span>
                    <input type="text" placeholder="E-mail" class="form-text" name="email" id="guest-email">
                </div>
                <div id="error_guest" class = "red-text"></div>
                <div class="form-item btn_next">
                    <input id='request_guest' type="button" value="Request" class="form-submit" />
                </div>
            </div>
        </div>
        <div id="guest_resp_form_block" class="popup_form">
            <div class="popup_title" style="border: none">Cool, We'll send you an invite soon!</div>
        </div>
        <!--end invite block for guest page-->

        <!-- start invite block -->
        <div id="landing_invite_form_block" class="popup_form">
            <h3 class="popup_title">Request an invite</h3>
            <div class="form-item">
                <span class="form-text_bg input_email"></span>
                <input type="text" placeholder="E-mail" class="form-text" name="email" id="invite-email" />
            </div>
            <div id="landing_invite_error" class="hidden landing_invite_error">
                <span class="error_line"></span>
            </div>
            <div id="landing_invite_success" class="landing_invite_success hidden">Thank you.</br>Your email has added to our database.</div>
            <div class="form-item btn_next">
                <input id="invite_request" type="button" value="Request" class="form-submit" />
            </div>
        </div>
        <!-- end invite block -->
    </div>
</div>

<div id="container_popup" class="container_popup">
    <div class="container_popup_wrap">
        <a href="javascript:void(0)" id="close_content_popup" class="close_popup" onclick="close_content_popup()">Close</a>
        <div id="content_popup" class="content_popup">
        </div>
    </div>
</div>
<div id="container_popup1" class="container_popup">
    <div class="container_popup_wrap">
        <a href="javascript:void(0)" id="close_content_popup" class="close_popup" onclick="close_content_popup1()">Close</a>
        <div id="content_popup1" class="content_popup">
        </div>
    </div>
</div>
<div id="delete_bookmark_popup" class = "hidden">
    <div id="delete_bookmark_content" >
        <div>
            Are you sure want to delete?
        </div>
        <div style="margin: auto; width: 220px;">
            <div class="form-item btn_next">
                <input type="button" value="Cansel" class="delBookmarks" style="margin:15px 20px 10px;" onclick="close_content_popup1()" />
            </div>
            <div class="form-item btn_next">
                <input  type="button" value="Delete" class="delBookmarks" style="margin:15px 20px 10px;" id="delBookmarkBtn" />
            </div>
            <div class = "hidden" id="id_bookmark_fordel"></div>
            <div class = "hidden" id="id_exp_fordel"></div>
        </div>
    </div>
</div>