<?php if(!empty($this->link_data)):?>
    <?php foreach($this->link_data as $news_key=>$news): ?>
        <div class="experience_content_item">
            <?php if(!empty($news['image'])): ?>
                <div class="experience_content_item_image"><img src="<?=$news['image']?>" alt="" /></div>
            <?php endif; ?>
            <div class="experience_content_item_title"><?=$news['title']?></div>
            <div class="experience_content_item_desc"><?=$news['content']?></div>
            <a href="javascript:void(0)" class="experience_news_link" 
               onclick ="opennews('<?=str_replace(array("'", '"', '&#39;'),"",$news['url'])?>', '<?= str_replace(array("'", '"','&#39;'),"" ,$news['title'])?>'<?if(!empty($news['image'])){echo ", '".$news['image']."'";}?> )"><?=$news['url']?></a>
        </div>
    <?php endforeach; ?>
    <?if($this->amount == 2):?>
        <a href="javascript:void(0)" class="more_link" onclick="getContent('news', 8, <?php print $this->id; ?>)">More...</a>
        <div class="block_loader"><img src="/img/ajax-loader_grey.gif" height="32px" width="32px;" /></div>
    <?endif;?>
<?php else: ?>
    <div class="experience_content_item">
        No news
    </div>
<?php endif; ?>