<? if (!empty($this->link_data)): ?>
    <? foreach ($this->link_data as $video): ?>
     <div class="experience_content_item">
        <div class="experience_content_item_image">
            <a href="javascript:void(0)" onclick="show_media(this, 'video')">
                <iframe width="560" height="315" src="http://www.youtube.com/embed/<?=$video['id']?>" frameborder="0" allowfullscreen class="original" name="<?=$video['title']?>"></iframe>
                <img src="<?=$video['thumbnail']?>" alt="" />
            </a>
        </div>
        <div class="experience_content_item_title"><?=$video['title']?></div>
        <div class="experience_content_item_desc"><?=$video['description']?></div>
    </div>        
   <? endforeach; ?>

<?if($this->amount == 2):?> 
    <a href="javascript:void(0)" class="more_link" onclick="getContent('videos', 10, <?= $this->id ?>)">More...</a>
    <div class="block_loader"><img src="/img/ajax-loader_grey.gif" height="32px" width="32px;" /></div>
<?endif;?>
<?else:?>
    <div class="experience_content_item">
     No videos
    </div>
<? endif; ?>

