<div class = "wrap">
    <div>
        <img class = "logotip" src="/img/logo.png" alt="" />
    </div>
    <div id ="logout"><a href="/admin/index/logout">Logout</a></div>
    <div class = "main">
        <a class = "console_item" href="/admin/index/requestconsole">Login console</a>
        <a class = "console_item" href="/admin/index/logoutrequestconsole">Logout console</a>
        <a class = "console_item" href="/admin/index/recommendationconsole">Recommenation console</a>
    </div>
</div>

<style>
    body{
        background: none repeat scroll 0 0 #FAFBFC;
    }
    tr:nth-child(even){
        background: #E4EBF2;
    }
    tr:nth-child(odd){
        background: #CCD6E0;
    }
    tr{
        padding: 3px;
    }
    h3{
        margin: 21px 20px 3px
    }
    button{
        margin-top: 20px; 
    }
    .wrap{
        width: 100%;
    }
    .console_item{
        margin: 0 15px;
    }
/*    .wrap div{
        margin: auto;
        width: 500px;
    }*/
    td{
        padding: 0 5px;
    }
    th{
        background: none repeat scroll 0 0 #599CBD;
    color: white;
    font-weight: 100;
    padding: 0 6px;
    text-align: center;
    }
    .cent{
        text-align: center;
    }
    td.delmai{
        background: white;
    }
    #logout{
        float: right;
        margin: 10px;
    }
    img.logotip{
        float: left;
        margin: 20px 20px 26px 21px;
    }
    .main{
        clear: both;
        margin-left: 70px;
        margin-top: 40px;
    }
    #er_msg{
        color: red;
        margin: 10px 0;
    }
</style>
