<script type="text/javascript">
    jQuery(document).ready(function(){
        jQuery("#dashboard-content").mCustomScrollbar({
            scrollInertia: 4,
            advanced:{
                updateOnContentResize:true
            }
        });
        //resize_bg();
        jQuery(window).resize(function(){
            //resize_bg();
        });
    });
</script>
<div id="dashboard-content" class="dashboard-content wiki_page">
    <div data-role="page" id="wiki" class="wiki_page_container">
        <div data-role="header" data-theme="a" data-position="fixed" data-id="head" data-add-back-btn="true"></div>
        <div id="reader_body" class="wiki_page_body">
            <h1 id="reader_title"><?php echo $this->title; ?><a style ="color: white;    font-size: large;    font-weight: bold;    padding-left: 47px;    text-decoration: none;"href="/default/dashboard/experience?id=<?php print $this->exp_id; ?>" class="add_experience_btn_link back_btn">Back</a></h1>
            <?php print $this->content; ?>
        </div>
    </div>
</div>