<script type="text/javascript">
    jQuery(document).ready(function(){
        jQuery("#conteiner").css("background","none");
        resize_bg();
    });
</script>
<div id="static_page_container" class="static_page_container">
    <div class="static_page_body">
        <h3>Our mission</h3>
        <p class="mission_slogan">“Splyst seeks to eliminate the noise of the web by matching information to the people who are interested in it.”</p>
        <p>We believe that information should find you, not the other way around. Splyst enhances the user’s online experience by allowing them to discover, organize and share the things they love and need. Splyst is a smart dashboard that allows a user to collect their internet experiences, learns their preferences, and returns to the user new information on the web that is relevant to them. Splyst constantly indexes millions of topic-specific streams from thousands of different sources to filter through the noise of the web and deliver customized internet experiences.</p>
        <h3>Team</h3>
        <div class="about_team">
            <div class="about_team_item">
                <div class="about_team_item_pic"><img src="/img/travis.png" /></div>
                <div class="about_team_item_post">CEO</div>
            </div>
            <div class="about_team_item">
                <div class="about_team_item_pic"><img src="/img/david.png" /></div>
                <div class="about_team_item_post">COO</div>
            </div>
        </div>
    </div>
</div>