<!DOCTYPE html>
<html lang="en">
    <head>
        <?=$this->partial("head.phtml"); ?> <!-- connect head -->
    </head>
    <body>
        <div id="wrapper" class="wrapper">
            <?php print $this->render("header.phtml"); ?> <!-- connect header -->
            <div id="conteiner" class="conteiner recommendation_page">
                <div id="left-sidebar" class="left-sidebar">
                    <?php print $this->partial("left-sidebar.phtml"); ?> <!-- connect left side-bar -->
                </div>
                <div class="container-center">
                    <div class="squeeze">
                        <div id="squeeze-bg" class="squeeze-bg">
                            <?php print $this->layout()->content; ?> <!-- connect content -->
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <?php print $this->partial("footer.phtml"); ?> <!-- connect footer -->
        <?php print $this->partial("pop-ups.phtml"); ?> <!-- connect pop-ups window -->
    </body>
</html>