<h1 class="h1_page1">Select experience</h1>
<div class="form-wrapper" style="width:705px">
    <form id="category-form" class="category_from" action="" method="POST">
        <div class="form-item checkbox first">
            <? foreach ($this->experience as $key=>$item): ?>
                <div class="checkbox-item">
                    <input id="category-<?=$item['exp_id']?>" type="checkbox" name="category[<?=$item['exp_id']?>]"
                           <?if($item['checked']== 1):?>checked="checked"<?endif;?> value="<?=$item['exp_id']?>"/>
                    <label for="category-"><?=$item['exp_title']?></label>
                </div>
                <?if (($key + 1) % 12 == 0): ?>
                </div>
                <div class="form-item checkbox<? if (!isset($this->experience[$key + 12])) print ' last'; ?>">
                <? endif; ?>
            <? endforeach; ?>
        </div>
        <div class="form-actions btn_next">
            <input id="next" type="button" class="form-submit" value="Next" />
        </div>
    </form>
</div>
<script>
    $(document).ready(function(){
        $('#next').click(function(){
            $('#category-form').submit();
        });
    });
</script>